title:       "Ömer Abdülaziz Kasapoğlu"
description: "desc"
url: "https://oakasapoglu.github.io"
baseurl: "/oakasapoglu"

author:
  name:    "Ömer Abdülaziz Kasapoğlu"
  email:   "oakasapoglu@gmail.com"
  github:  "oakasapoglu"
  twitter: "oakasapoglu"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-org
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

whitelist:
  - jekyll-org

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/
