title: "Your Name"
description: "desc"
url: "https://oakasapoglu.github.io"
baseurl: "/oakasapoglu"

author:
  name: "Your Name"
  email: "you@example.com"
#  github: "yourusername"
#  twitter: "yourhandle"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-org
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/
